apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: client
          image: aviendre/cdc_3004-client:latest
          env:
            - name: PORT
              value: "8000"

            #Specify NodePort Service Port for the Server
            - name: SERVER_PORT
              value: "30081"
          ports:
            - containerPort: 8000
        - name: server
          image: aviendre/cdc_3004-server:latest
          env:
            - name: PORT
              value: "8001"
            - name: AWS_ACCESS_KEY_ID
              value: AKIATATDQXXRG65H6AUH
            - name: AWS_SECRET_ACCESS_KEY
              value: 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
            - name: AWS_REGION
              value: ap-southeast-1
            - name: AWS_VIDEO_BUCKET_NAME
              value: cdcvideobucket
            - name: AWS_VIDEO_BUCKET_PREFIX
              value: videos/
            - name: AWS_IMAGE_BUCKET_NAME
              value: cdcimagebucket
            - name: AWS_IMAGE_BUCKET_PREFIX
              value: images/
            - name: AWS_ANALYSIS_BUCKET_NAME
              value: cdcanalysisbucket
            - name: AWS_ANALYSIS_BUCKET_PREFIX
              value: analysis/
            - name: EMAIL_ADDRESS
              value: ridhwanproper@gmail.com
            - name: EMAIL_PASSWORD
              value: kdymcgvlkzehfqjb
            - name: SMTP_SERVER
              value: smtp.gmail.com
          ports:
            - containerPort: 8001
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-deployment
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80

---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: NodePort
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080
      name: client-port
    - protocol: TCP
      port: 8001
      targetPort: 8001
      nodePort: 30081
      name: server-port
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
spec:
  rules:
    - http:
        paths:
          - path: /client
            pathType: Prefix
            backend:
              service:
                name: app-service
                port:
                  number: 8000
          - path: /server
            pathType: Prefix
            backend:
              service:
                name: app-service
                port:
                  number: 8001
