version: "3"

services:
  client:
    build:
      context: client
      target: builder
    stop_signal: SIGINT
    ports:
      - "8000:8000"

  server:
    build:
      context: server
      target: builder
    stop_signal: SIGINT
    ports:
      - "8001:8001"
